Fix support for cryptography >=39 <42
TypeError: Backend.load_pem_private_key() missing 1 required positional argument: 'unsafe_skip_rsa_key_validation'